const apiKey = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
export const isFirebaseConfigured = Boolean(apiKey && process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN && process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID && process.env.NEXT_PUBLIC_FIREBASE_APP_ID);
const storageKey = 'firebaseAdminSession';
function readSession() { if (typeof window === 'undefined') return null; try { return JSON.parse(sessionStorage.getItem(storageKey) || 'null'); } catch { return null; } }
function saveSession(session) { sessionStorage.setItem(storageKey, JSON.stringify(session)); }
export async function signInAdministrator(email, password) { const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, returnSecureToken: true }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message?.replaceAll('_', ' ') || 'Could not sign in.'); saveSession({ idToken: data.idToken, refreshToken: data.refreshToken, expiresAt: Date.now() + Number(data.expiresIn || 3600) * 1000 - 60000 }); return data; }
export async function getAdminToken() { const session = readSession(); if (!session) return null; if (session.expiresAt > Date.now()) return session.idToken; const response = await fetch(`https://securetoken.googleapis.com/v1/token?key=${apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'refresh_token', refresh_token: session.refreshToken }) }); const data = await response.json(); if (!response.ok) { clearAdminToken(); return null; } const next = { idToken: data.id_token, refreshToken: data.refresh_token, expiresAt: Date.now() + Number(data.expires_in || 3600) * 1000 - 60000 }; saveSession(next); return next.idToken; }
export async function sendAdministratorReset(email) { const response = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=${apiKey}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestType: 'PASSWORD_RESET', email }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message?.replaceAll('_', ' ') || 'Could not send the reset email.'); }
export const clearAdminToken = () => typeof window === 'undefined' || sessionStorage.removeItem(storageKey);
