import { readSermons, writeSermons } from '../../../../lib/server/jsonbin';
import { requireAdmin } from '../../../../lib/server/firebaseAdmin';

export const dynamic = 'force-dynamic';
const reply = (data, status = 200) => Response.json(data, { status, headers: { 'Cache-Control': 'no-store' } });
const statusFor = (error) => /required|access|sign in/i.test(error.message) ? 401 : 500;
function sermon(input, existing) { const title = String(input.title || '').trim(); const mediaUrl = String(input.mediaUrl || '').trim(); const publishedAt = String(input.publishedAt || '').trim(); if (!title || title.length > 160) throw new Error('Enter a sermon title of up to 160 characters.'); if (!mediaUrl || !/^https:\/\//i.test(mediaUrl)) throw new Error('Enter a valid https:// message link.'); if (!publishedAt || Number.isNaN(new Date(publishedAt).getTime())) throw new Error('Enter a valid sermon date.'); return { ...existing, title, mediaUrl, publishedAt, speaker: String(input.speaker || '').trim(), description: String(input.description || '').trim(), isPublished: Boolean(input.isPublished), updatedAt: new Date().toISOString() }; }
export async function PATCH(request, { params }) { try { await requireAdmin(request); const { id } = await params; const sermons = await readSermons(); const index = sermons.findIndex((item) => item.id === id); if (index === -1) return reply({ error: 'Sermon not found.' }, 404); sermons[index] = sermon(await request.json(), sermons[index]); await writeSermons(sermons); return reply(sermons[index]); } catch (error) { return reply({ error: error.message || 'Unable to update sermon.' }, statusFor(error)); } }
export async function DELETE(request, { params }) { try { await requireAdmin(request); const { id } = await params; const sermons = await readSermons(); const remaining = sermons.filter((item) => item.id !== id); if (remaining.length === sermons.length) return reply({ error: 'Sermon not found.' }, 404); await writeSermons(remaining); return reply({ success: true }); } catch (error) { return reply({ error: error.message || 'Unable to delete sermon.' }, statusFor(error)); } }
